### PR TITLE
Fix small bug in OSM.org import.

### PR DESCRIPTION
**Pull request by noffle**

### CODE REVIEW

**Comment by dereklieu** [comment]
@noffle was this causing issues before? I moved [that line](https://github.com/osmlab/field-data-coordinator/pull/37/files#diff-c8c8bcfbad4656e860b3b9bab4ecd485L73) to the `wipeDb` function since that made more sense to me, although it certainly didn't help code readability.

**Comment by noffle** [comment]
@dereklieu I didn't notice that you already added this! Strange: without the line I added I get lockfile errors when the new `osmOrgDb` is created and we try to write to it. Digging..

**Comment by noffle** [comment]
Ah ha, I was seeing different behaviour because there's a race condition in `osm-p2p-db-importer`! Fixed in `1.1.1`.

**Comment by noffle** [comment]
All right, now this PR is just a version bump to a dep.

**Comment by noffle** [comment]
Thanks @dereklieu! :taco:

**Pull request merged**
