### PR TITLE
[WIP] Send OSM XML over the OSM.org sync stream instead of osm-p2p-db replication.

### PR DESCRIPTION
**Pull request by noffle**
This is the coordinator app's half of an optimization to get sync working a bit faster until osm-p2p-db is a bit quicker at syncing larger datasets.

Collector app PR: https://github.com/osmlab/field-data-collection/pull/142

### CODE REVIEW

**Comment by dereklieu** [comment]
Do we still need to up an instance of `osmOrgDb` if we're just storing this in a local xml file? If not, might be worth removing those pieces, plus the `bboxQuerySavedOsm` method, to avoid any confusion going forward.

**Comment by noffle** [comment]
@dereklieu We still need the OSM.org osm-p2p-db so that we can render OSM features on the coordinator, and for dedupe'ing placeholder nodes created by collectors.

**Comment by noffle** [comment]
@dereklieu You didn't know this, but in the future, please hold back on merging any of my PRs marked "[WIP]". I was looking for review comments, but the work isn't completely finished yet. It'll be fine though -- I don't think this'll bite anyone.

**Comment by dereklieu** [comment]
@noffle ah I thought that might have been the case but should have checked with you. It happened that something I was working on touched this part of the code, so I wanted to merge it sooner. Will keep that in mind for the future though.

**Pull request merged**
